name: Node.js CI

on:
  [ push, pull_request ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run make
      - name: Publish package
        run: npm run publish && node hash.js
        if: ${{ github.ref == 'refs/heads/VLE-690_calculate_sha256_from_installer' && github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SHA256 Hash File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/reposTraficom/lem-ui/releases/${{ github.event.release.id }}/assets"
          asset_path: out/prod/make/squirrel.windows/x64/sha256sum.txt
          asset_name: sha256sum.txt
          asset_content_type: text/plain
