
name: Node.js CI

on:
  [ push, pull_request ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - name: Log Tag Name
        run: echo ${{ github.tag_name }}
      - run: npm run make
      - name: Publish package
        run: npm run publish --verbose
        if: ${{ github.ref == 'refs/heads/VLE-690_calculate_sha256_from_installer' && github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: node hash.js
      - name: Get Release Upload URL
        run: |
          response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Traficom/lem-ui/releases/tags/${{ github.event.release.tag_name }})
          upload_url=$(echo "$response" | jq -r '.upload_url')
          echo "Upload URL: $upload_url"
      - name: Upload SHA256 Hash File
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: out/prod/make/squirrel.windows/x64/sha256sum.txt
          asset_name: sha256sum.txt
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
